language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:hroptatyr/ppa -y
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq libev-dev
  - sudo apt-get install -qq unserding
  - sudo apt-get install -qq uterus
  - sudo apt-get install -qq libfixc

before_script:
  - autoreconf -vfi

script:
  - mkdir \=build
  - cd \=build
  - ../configure $OPTIONS
  - make clean all check distcheck

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
