language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:hroptatyr/ppa -y
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq libev-dev
  - sudo apt-get install -q unserding
  - sudo apt-get install -q uterus
  - sudo apt-get install -q libfixc

before_script:
  - autoreconf -vfi

script:
  - mkdir \=build
  - cd \=build
  - ../configure $OPTIONS || { cat config.log; false; }
  - make clean all check || { cat test/test-suite.log; false; }
  - make distcheck

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
